### ISSUE TITLE
Unable to fetch error

### ISSUE THREAD

**Issue by chi1992** [chi1992/TenderSearch#1]
Traceback (most recent call last):
  File "C:\Program Files\Python_3_7_4\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python_3_7_4\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:/Users/Chase.Chi/source/repos/chi1992/TenderSearch/main.py", line 52, in execute
    dict_parsed = self.holder_webParser.get_dataDictOfDate(date, var_state)
  File "c:\Users\Chase.Chi\source\repos\chi1992\TenderSearch\holder_webParser.py", line 24, in get_dataDictOfDate    
    list_isanztec = self.parse_rawToIsAgreement(cnt_anztec)
  File "c:\Users\Chase.Chi\source\repos\chi1992\TenderSearch\holder_webParser.py", line 55, in parse_rawToIsAgreement
    htmlObj = self.parser(cnt_isagreement)[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by chi1992** [comment]
Solved by add an empty list unhappy case at start of parse_rawToIsAgreement() method.
Problem source is not clear.
